//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommTcper.SRWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApbApplyForDTO", Namespace="http://request.object.rockwell.com")]
    [System.SerializableAttribute()]
    public partial class ApbApplyForDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productionLineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.orderIdField, value) != true)) {
                    this.orderIdField = value;
                    this.RaisePropertyChanged("orderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productionLine {
            get {
                return this.productionLineField;
            }
            set {
                if ((object.ReferenceEquals(this.productionLineField, value) != true)) {
                    this.productionLineField = value;
                    this.RaisePropertyChanged("productionLine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApbGiveBackDTO", Namespace="http://request.object.rockwell.com")]
    [System.SerializableAttribute()]
    public partial class ApbGiveBackDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CommTcper.SRWeb.ArrayOfString barcodesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string orderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string productionLineField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CommTcper.SRWeb.ArrayOfString barcodes {
            get {
                return this.barcodesField;
            }
            set {
                if ((object.ReferenceEquals(this.barcodesField, value) != true)) {
                    this.barcodesField = value;
                    this.RaisePropertyChanged("barcodes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string orderId {
            get {
                return this.orderIdField;
            }
            set {
                if ((object.ReferenceEquals(this.orderIdField, value) != true)) {
                    this.orderIdField = value;
                    this.RaisePropertyChanged("orderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string productionLine {
            get {
                return this.productionLineField;
            }
            set {
                if ((object.ReferenceEquals(this.productionLineField, value) != true)) {
                    this.productionLineField = value;
                    this.RaisePropertyChanged("productionLine");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://production.rockwell.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://production.rockwell.com", ConfigurationName="SRWeb.AutoPastingBarcodeServicePortType")]
    public interface AutoPastingBarcodeServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string applyForBarcode(CommTcper.SRWeb.ApbApplyForDTO in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> applyForBarcodeAsync(CommTcper.SRWeb.ApbApplyForDTO in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string giveBackBarcode(CommTcper.SRWeb.ApbGiveBackDTO in0);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> giveBackBarcodeAsync(CommTcper.SRWeb.ApbGiveBackDTO in0);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AutoPastingBarcodeServicePortTypeChannel : CommTcper.SRWeb.AutoPastingBarcodeServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoPastingBarcodeServicePortTypeClient : System.ServiceModel.ClientBase<CommTcper.SRWeb.AutoPastingBarcodeServicePortType>, CommTcper.SRWeb.AutoPastingBarcodeServicePortType {
        
        public AutoPastingBarcodeServicePortTypeClient() {
        }
        
        public AutoPastingBarcodeServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoPastingBarcodeServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoPastingBarcodeServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoPastingBarcodeServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string applyForBarcode(CommTcper.SRWeb.ApbApplyForDTO in0) {
            return base.Channel.applyForBarcode(in0);
        }
        
        public System.Threading.Tasks.Task<string> applyForBarcodeAsync(CommTcper.SRWeb.ApbApplyForDTO in0) {
            return base.Channel.applyForBarcodeAsync(in0);
        }
        
        public string giveBackBarcode(CommTcper.SRWeb.ApbGiveBackDTO in0) {
            return base.Channel.giveBackBarcode(in0);
        }
        
        public System.Threading.Tasks.Task<string> giveBackBarcodeAsync(CommTcper.SRWeb.ApbGiveBackDTO in0) {
            return base.Channel.giveBackBarcodeAsync(in0);
        }
    }
}
